kind: PersistentVolume
apiVersion: v1
metadata:
  name: logs-pv-NAMESPACE
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/log"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs-pvc-NAMESPACE
  namespace: NAMESPACE
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4.9Gi

